// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6baOL3Uh65zYMGmsC95R41W_iUBGZme4',
    appId: '1:822148080954:web:b4cae13433cd56dd101c03',
    messagingSenderId: '822148080954',
    projectId: 'chat-app-95bf5',
    authDomain: 'chat-app-95bf5.firebaseapp.com',
    storageBucket: 'chat-app-95bf5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFVtSBvkB3CHrMabaa8q1sB3p2I8sMeS4',
    appId: '1:822148080954:android:4d4c81030274ad9a101c03',
    messagingSenderId: '822148080954',
    projectId: 'chat-app-95bf5',
    storageBucket: 'chat-app-95bf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAO8HvgsUImWQiACvw_HFqJXvg0WvKqZE',
    appId: '1:822148080954:ios:8c8875f5e026c027101c03',
    messagingSenderId: '822148080954',
    projectId: 'chat-app-95bf5',
    storageBucket: 'chat-app-95bf5.appspot.com',
    iosBundleId: 'com.example.whatsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAO8HvgsUImWQiACvw_HFqJXvg0WvKqZE',
    appId: '1:822148080954:ios:23b524356f7321a3101c03',
    messagingSenderId: '822148080954',
    projectId: 'chat-app-95bf5',
    storageBucket: 'chat-app-95bf5.appspot.com',
    iosBundleId: 'com.example.whatsApp.RunnerTests',
  );
}
